const popularCities = [
    "New York", "London", "Los Angeles", "Chicago",
    "Berlin","Rome","Whasington DC","Detroit",
    "Wyoming",
    "Paris",
    "California",
    "Springfield",
    "Pennsylvania",
    "Marrakech",
    "Rabat",
    "Alger",
    "Tunis",
    "Pretoria",
    "Abuja",
    "Bamako",
    "Dakar",
    "Abidjan",
    "Nouakchott",
    "Ottawa",
    "Buenos Aires",
    "Brasilia",
    "Seattle",
    "Texas",
    "Tokyo",
    "Shibuya",
    "Dubai",
    "Philadelphia",
    "San Diego",
    "San Francisco",
    "Madrid",
    "Cairo",
    "Lisbonne",
    "Delhi",
    "Jakarta",
    "Amsterdam",
    "Hong Kong",
    "Singapore",
    "Bangkok",
    "Istanbul",
    "Brazzaville",
    "Libreville"
]

export default popularCities;